import AuthGuard from "@/components/authGuard/authGuard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}
